default:
  image: teamparallax/unoconv-alpine:v1.1.4

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .npm/

stages:
  - prepare
  - test
  - build
  - post

before_script:
  - yarn install --cache .npm --prefer-offline

install_dependencies:
  stage: prepare
  script:
    - yarn install

test_lint:
  stage: test
  script:
    - yarn run lint

test_unit:
  stage: test
  script:
    - yarn run test

test_quality:
  image:
    name: eu.gcr.io/parallax-gitlab/sonarqube:latest
    entrypoint: [""]
  stage: post
  variables:
    SONAR_TOKEN: ${SONAR_TOKEN}
    SONAR_HOST_URL: "https://sonar.cloud.team-parallax.com/"
    GIT_DEPTH: 0
  script:
    - yarn install parallax-common-config@`node -p -e "require('./package.json').devDependencies['parallax-common-config']"`
    - sonar-scanner -Dsonar.projectKey=belwue-${CI_PROJECT_NAME} -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - tags
    - master
