default:
  image: teamparallax/unoconv-alpine:v1.1.4

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .npm/

stages:
  - prepare
  - test
  - build
  - post

before_script:
  - yarn install --cache .npm --prefer-offline

install_dependencies:
  stage: prepare
  script:
    - yarn install

test_lint:
  stage: test
  script:
    - yarn run lint

test_unit:
  stage: test
  script:
    - yarn run test

build_docker_tagged:
  stage: build
  services:
      - docker:dind
  image: docker:latest
  before_script:
      - echo "Build docker image"
  variables:
      IMAGE: ${IMAGE_BASE_NAME}
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      DOCKER_USER: ${DOCKER_USER}
      DOCKER_TLS_CERTDIR: ""
      REGISTRY: ${REGISTRY}
  script:
    - echo "${CI_COMMIT_TAG}"
    - echo -n "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USER} --password-stdin ${REGISTRY}
    - docker build -t ${IMAGE}:${CI_COMMIT_TAG} -f ./Dockerfile .
    - docker push ${IMAGE}:${CI_COMMIT_TAG}
    - docker logout
  only:
    - tags

test_quality:
  image:
    name: eu.gcr.io/parallax-gitlab/sonarqube:latest
    entrypoint: [""]
  stage: post
  variables:
    SONAR_TOKEN: ${SONAR_TOKEN}
    SONAR_HOST_URL: "https://sonar.cloud.team-parallax.com/"
    GIT_DEPTH: 0
  script:
    - yarn install parallax-common-config@`node -p -e "require('./package.json').devDependencies['parallax-common-config']"`
    - sonar-scanner -Dsonar.projectKey=belwue-${CI_PROJECT_NAME} -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - tags
    - master
