apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.web.name }}
    labels:
        app-name: {{ .Values.web.name }}
spec:
    ports:
        - name: http
          port: 80
          targetPort: 3000
    selector:
        app-name: {{ .Values.web.name }}
